import React from 'react'
import { CheckCircle } from 'lucide-react'
import { OPERATION_MODES, OWNERSHIP_OPTIONS } from '../../constants/options'
import { BANGLADESH_DIVISIONS, DIVISION_DISTRICTS_MAP, getDistrictBranches } from '../../constants/bdLocations'

const text = {
  en: { title: 'Trade License & Entity Details', operation: 'Operation Mode', proposal: 'Proposal Type', business: 'Business Name', entity: 'Type of Entity', product: 'Business Product', start: 'Business Start Date', employees: 'Number of Employees', ownership: 'Majority Ownership Status', tradeNumber: 'Trade License Number', issue: 'Issue Date', expiry: 'Expiry Date', authority: 'Issue Authority', etin: 'e-TIN', etinVerified: 'e-TIN Verified', trc: 'TRC', bin: 'BIN Info', growth: 'Annual Business Growth (%)', address: 'Registered Address', division: 'Division', district: 'District', branch: 'Nearest Branch', back: 'Back', next: 'Next' },
  bn: { title: 'ট্রেড লাইসেন্স ও সত্তা বিবরণ', operation: 'পরিচালনার মোড', proposal: 'প্রস্তাবের ধরন', business: 'ব্যবসার নাম', entity: 'প্রতিষ্ঠানের ধরন', product: 'ব্যবসায়িক পণ্য', start: 'ব্যবসা শুরুর তারিখ', employees: 'কর্মীদের সংখ্যা', ownership: 'সংখ্যাগরিষ্ঠ মালিকানা স্ট্যাটাস', tradeNumber: 'ট্রেড লাইসেন্স নম্বর', issue: 'জারির তারিখ', expiry: 'মেয়াদ শেষ', authority: 'জারিকারী কর্তৃপক্ষ', etin: 'ই-টিআইএন', etinVerified: 'ই-টিআইএন যাচাইকৃত', trc: 'টিআরসি', bin: 'বিআইএন তথ্য', growth: 'বার্ষিক ব্যবসায়িক বৃদ্ধি (%)', address: 'নিবন্ধিত ঠিকানা', division: 'বিভাগ', district: 'জেলা', branch: 'নিকটতম শাখা', back: 'পিছনে', next: 'পরবর্তী' }
}

export default function Step5({ prev, next, data, setData, language }) {
  const lang = text[language] || text.en
  const form = { entityType: 'PROPRIETORSHIP', proposalType: 'NEW', businessName: data.business?.businessName || '', division: 'Dhaka', district: 'Dhaka', nearestBranch: '', ...data.trade }
  const update = fields => setData('trade', fields)
  const districts = DIVISION_DISTRICTS_MAP[form.division] || []
  const branches = getDistrictBranches(form.district)
  const input = (key, type = 'text', readOnly = false) => <input type={type} value={form[key] || ''} onChange={e => update({ [key]: e.target.value })} readOnly={readOnly} className={`w-full rounded-lg border border-gray-300 p-2 focus:outline-none focus:ring-2 focus:ring-primary ${readOnly ? 'cursor-not-allowed bg-gray-100' : ''}`} />
  const field = (label, key, type = 'text', readOnly = false) => <div><label className="mb-1 block text-sm font-medium text-gray-700">{label}</label>{input(key, type, readOnly)}</div>

  return <div><h2 className="mb-4 text-2xl font-bold text-primary">{lang.title}</h2><div className="space-y-4">
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label className="mb-1 block text-sm font-medium text-gray-700">{lang.operation}</label><select value={form.operationMode} onChange={e => update({ operationMode: e.target.value })} className="w-full rounded-lg border border-gray-300 p-2">{OPERATION_MODES.map(item => <option key={item}>{item}</option>)}</select></div><div>{field(lang.proposal, 'proposalType', 'text', true)}</div></div>
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">{field(lang.business, 'businessName', 'text', true)}{field(lang.entity, 'entityType', 'text', true)}</div>
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">{field(lang.product, 'businessProduct')}{field(lang.start, 'startDate', 'date')}{field(lang.employees, 'employees', 'number')}</div>
    <div><label className="mb-1 block text-sm font-medium text-gray-700">{lang.ownership}</label><select value={form.ownership} onChange={e => update({ ownership: e.target.value })} className="w-full rounded-lg border border-gray-300 p-2">{OWNERSHIP_OPTIONS.map(item => <option key={item}>{item}</option>)}</select></div>
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">{field(lang.tradeNumber, 'tradeNumber')}{field(lang.issue, 'issueDate', 'date')}{field(lang.expiry, 'expiryDate', 'date')}{field(lang.authority, 'issueAuthority')}</div>
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{field(lang.etin, 'eTin')}<div><label className="mb-1 block text-sm font-medium text-gray-700">{lang.etinVerified}</label><div className="flex h-10 items-center gap-1 rounded-lg bg-green-50 px-3 text-sm text-green-700">{form.eTinVerified ? <><CheckCircle className="h-4 w-4" /> Yes</> : 'Pending'}</div></div>{field(lang.trc, 'trc')}{field(lang.bin, 'bin')}</div>
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">{field(lang.growth, 'businessGrowth', 'number')}<div><label className="mb-1 block text-sm font-medium text-gray-700">{lang.address}</label><textarea value={form.registeredAddress || ''} onChange={e => update({ registeredAddress: e.target.value })} rows="2" className="w-full rounded-lg border border-gray-300 p-2" /></div></div>
    <div className="grid grid-cols-1 gap-4 border-t border-gray-200 pt-4 sm:grid-cols-3"><div><label className="mb-1 block text-sm font-medium text-gray-700">{lang.division}</label><select value={form.division} onChange={e => update({ division: e.target.value, district: '', nearestBranch: '' })} className="w-full rounded-lg border border-gray-300 p-2">{BANGLADESH_DIVISIONS.map(item => <option key={item}>{item}</option>)}</select></div><div><label className="mb-1 block text-sm font-medium text-gray-700">{lang.district}</label><select value={form.district} onChange={e => update({ district: e.target.value, nearestBranch: '' })} className="w-full rounded-lg border border-gray-300 p-2"><option value="">Select district</option>{districts.map(item => <option key={item}>{item}</option>)}</select></div><div><label className="mb-1 block text-sm font-medium text-gray-700">{lang.branch}</label><select value={form.nearestBranch} onChange={e => update({ nearestBranch: e.target.value })} disabled={!form.district} className="w-full rounded-lg border border-gray-300 p-2"><option value="">Select branch</option>{branches.map(item => <option key={item}>{item}</option>)}</select></div></div>
    <div className="flex justify-between pt-4"><button onClick={() => prev()} className="rounded-lg border border-gray-300 px-6 py-2 font-medium">{lang.back}</button><button onClick={() => next()} className="rounded-lg bg-primary px-6 py-2 font-medium text-white">{lang.next}</button></div>
  </div></div>
}
